### ISSUE TITLE
Create select restaurants fragment

### ISSUE THREAD

**Issue by fangjingyan** [martinhu1994/weat#7]
As a user, 
I want to have some customized choice,
So that I can decide which restaurants shown on the roulette.
Open
[  ] Add category buttons, price buttons, rating buttons and the submit button
In Development
[  ] Send the options to the backend after clicking the submit button
Ready for evaluation
[  ] Get the restaurants names from backend and return them to the roulette fragment 
Completed
[  ] Support the backend to return the restaurants meeting the users' requirements

**Comment by wadmlkas** [comment]
This part decides on conditions that will be sent to back end as well as getting restaurant results from severs.
